# Generated by Django 3.1.7 on 2021-03-20 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='organization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=1000)),
                ('email', models.EmailField(max_length=254)),
                ('img', models.ImageField(upload_to='pics')),
                ('number', models.IntegerField()),
                ('password', models.CharField(max_length=200)),
                ('des', models.TextField()),
            ],
        ),
    ]
