# Generated by Django 3.1.7 on 2021-03-21 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organization',
            name='img',
        ),
        migrations.AlterField(
            model_name='organization',
            name='number',
            field=models.CharField(max_length=10),
        ),
    ]
