# Generated by Django 3.1.7 on 2021-03-23 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20210321_1856'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='pics'),
        ),
    ]
