# Generated by Django 3.1.7 on 2021-03-23 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_organization_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='email',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='organization',
            name='number',
            field=models.IntegerField(),
        ),
    ]
