# Generated by Django 3.1.7 on 2021-03-28 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_remove_organization_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='cammount',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
