# Generated by Django 3.1.7 on 2021-03-28 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_organization_cammount'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='Dname',
            field=models.TextField(blank=True, null=True),
        ),
    ]
